# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'PasswordEntryControl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Masonry'
  # Pods for PasswordEntryControl

  target 'PasswordEntryControlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PasswordEntryControlUITests' do
    # Pods for testing
  end

end
